name: Nightly

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build:
    name: Publish escript for every merge to main
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
      with:
          otp-version: '26'
    - name: Compile
      run: ./bootstrap
    - name: CT tests
      run: ./rebar3 ct

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy rebar3 escript to S3
      run: |
        aws s3 cp ./rebar3 s3://rebar3-nightly
