name: Publish

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:
    name: Create release and publish escript for every new tag
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
      with:
          otp-version: '26'
    - name: Compile
      run: ./bootstrap
    - name: CT tests
      run: ./rebar3 ct

    - name: Attest Build Provenance
      id: attest
      uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6 # v4.2.0
      with:
        subject-path: ./rebar3

    - name: Copy Attestation Bundle
      run: cp "${ATTESTATION}" rebar3.sigstore
      env:
        ATTESTATION: ${{ steps.attest.outputs.bundle-path }}

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release create \
          --repo "${GITHUB_REPOSITORY}" \
          --title "${GITHUB_REF_NAME}" \
          --generate-notes \
          "${GITHUB_REF_NAME}"

    - name: Upload Release Assets
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release upload --clobber "${GITHUB_REF_NAME}" \
          --repo "${GITHUB_REPOSITORY}" \
          rebar3 \
          rebar3.sigstore

    - name: Configure AWS credentials
      if: "!github.event.release.prerelease"
      uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy rebar3 escript to S3
      if: "!github.event.release.prerelease"
      run: |
        aws s3 cp ./rebar3 s3://rebar3
