name: Publish

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  build:
    name: Create release and publish escript for every new tag
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
      with:
          otp-version: '26'
    - name: Compile
      run: ./bootstrap
    - name: CT tests
      run: ./rebar3 ct

    - name: Attest Build Provenance
      id: attest
      uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
      with:
        subject-path: ./rebar3

    - name: Copy Attestation Bundle
      run: cp "${ATTESTATION}" rebar3.sigstore
      env:
        ATTESTATION: ${{ steps.attest.outputs.bundle-path }}

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release create \
          --repo "${GITHUB_REPOSITORY}" \
          --title "${GITHUB_REF_NAME}" \
          --generate-notes \
          "${GITHUB_REF_NAME}"

    - name: Upload Release Assets
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release upload --clobber "${GITHUB_REF_NAME}" \
          --repo "${GITHUB_REPOSITORY}" \
          rebar3 \
          rebar3.sigstore

    - name: Configure AWS credentials
      if: "!github.event.release.prerelease"
      uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Copy rebar3 escript to S3
      if: "!github.event.release.prerelease"
      run: |
        aws s3 cp ./rebar3 s3://rebar3
